name: SmartSort
version: 1.1.0
main: com.Alakaii.smartsort.SmartSortPlugin
author: Alakaii
description: Smart inventory and chest sorting plugin with shift+right-click functionality
website: https://github.com/Alakaii/SmartSort
api-version: 1.21

commands:
  smartsort:
    description: Main SmartSort command
    usage: /smartsort [reload|help]
    permission: smartsort.use
    aliases: [ss, ssort]

permissions:
  smartsort.use:
    description: Allows player to use SmartSort functionality (legacy permission, grants all sorting)
    default: false
  smartsort.containers.sort:
    description: Allows sorting of containers (chests, barrels, shulkers, etc.)
    default: false
  smartsort.inventory.sort:
    description: Allows sorting of player inventory
    default: false
  smartsort.containers.chest:
    description: Allows sorting of chests and trapped chests
    default: false
  smartsort.containers.barrel:
    description: Allows sorting of barrels
    default: false
  smartsort.containers.shulkerbox:
    description: Allows sorting of shulker boxes
    default: false
  smartsort.containers.enderchest:
    description: Allows sorting of ender chests
    default: false
  smartsort.containers.hopper:
    description: Allows sorting of hoppers
    default: false
  smartsort.containers.dispenser:
    description: Allows sorting of dispensers
    default: false
  smartsort.containers.dropper:
    description: Allows sorting of droppers
    default: false
  smartsort.admin:
    description: Admin commands including reload
    default: op
  smartsort.*:
    description: All SmartSort permissions
    default: op
    children:
      smartsort.use: true
      smartsort.containers.sort: true
      smartsort.inventory.sort: true
      smartsort.containers.chest: true
      smartsort.containers.barrel: true
      smartsort.containers.shulkerbox: true
      smartsort.containers.enderchest: true
      smartsort.containers.hopper: true
      smartsort.containers.dispenser: true
      smartsort.containers.dropper: true
      smartsort.admin: true

depend: []
softdepend: [WorldGuard, LWC, Towny, GriefPrevention, Residence]
